version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true